let language = {
    "HIS_GUI_HAND": "Hand",
    "HIS_GUI_GAME": "Game",
    "HIS_GUI_GAMETYPE": "Real/Practice",
    "HIS_GUI_GAMEKIND": "Game Type",
    "HIS_GUI_LATEST": "Latest",
    "HIS_GUI_HANDS": "Hands",
    "HIS_GUI_SEARCH": "SEARCH",
    "HIS_GUI_PERIOD": "Period",
    "HIS_GUI_NODATA": "No data",
    "HIS_GUI_DETAILS": "Details",
    "HIS_GUI_DATETIME": "Date & Time",
    "HIS_GUI_LIMIT": "Limit",
    "HIS_GUI_TABLENAME": "Table Name",
    "HIS_GUI_WINLOSS": "Win/Loss",
    "HIS_GUI_BACK": "BACK",
    "HIS_GUI_FORWARD": "FORWARD",
    "HIS_GUI_NUMBEROFHANDS": "Number of hands",
    "HIS_GUI_HANDNO": "Hand number",
    "HIS_GUI_FIRST": "<< Start",
    "HIS_GUI_FIRSTTEXT": "Start",
    "HIS_GUI_PREVIOUS": "< Previous",
    "HIS_GUI_PREVIOUSTEXT": "Previous hands",
    "HIS_GUI_NEXT": "Next >",
    "HIS_GUI_NEXTTEXT": "Next hands",
    "HIS_GUI_LAST": "End >>",
    "HIS_GUI_LASTTEXT": "End",
    "HIS_GUI_INTEXT": "In text",
    "HIS_GUI_VERTICALVIEW": "Vertical View",
    "HIS_GUI_HORIZONTALVIEW": "Horizontal View",
    "HIS_GUI_SESSIONS": "Sessions(s)",
    "HIS_GUI_VIEWREPLAY": "View Hand Replay",
    "HIS_GUI_VIEWROUNDS": "View Rounds",
    "HIS_GUI_POT": "Pot",
    "HIS_GUI_BET": "Bet",
    "HIS_GUI_WINNER": "Winner",
    "HIS_GUI_WINNERS": "Winner(s)",
    "HIS_GUI_YEAR": "Year",
    "HIS_GUI_MONTH": "Month",
    "HIS_GUI_DATE": "Date",
    "HIS_GUI_PLEASEWAIT": "Please wait, previous request in progress.",
    "HIS_GUI_PLAYERINFO": "Player Details",
    "HIS_GUI_HANDDETAILS": "Hand Details",
    "HIS_GUI_TABLETOURNEYID": "AAMS Session ID",
    "HIS_GUI_TICKETID": "AAMS Ticket ID",
    "HIS_GUI_SBBB": "SB/BB",
    "HIS_GUI_BETLIMITS": "Bet Limits",
    "HIS_GUI_RAKEID": "Rake ID",
    "HIS_GUI_TABLEID": "Table",
    "HIS_GUI_BACKCARD": "N/A",
    "HIS_DROPDOWN_ALL": "All",
    "GAME_THM": "Texas Hold'em",
    "GAME_OMA": "Omaha",
    "GAME_OMATU": "Omaha",
    "GAME_OMAHL": "Omaha Hi/Lo",
    "GAME_OMAHLTU": "Omaha Hi/Lo",
    "GAME_SCS": "Seven Card Stud",
    "GAME_FCS": "Five Card Stud",
    "GAME_FCD": "Five Card Draw",
    "GAME_FCD7A": "Five Card Draw 7-A",
    "GAME_TEL": "Americana",
    "GAME_SOKO": "Soko",
    "GAMETYPE_REAL": "Real",
    "GAMETYPE_PRACTISE": "Practice",
    "GAMEKIND_CASH": "Cash Game",
    "GAMEKIND_SITGO": "Sit & Go",
    "GAMEKIND_TOURNAMENT": "Tournament",
    "ANONYMOUS_TABLE": "Anonymous Character Cash Table",
    "NOLIMIT": "No Limit",
    "NL": "No Limit",
    "LI5": "Limit 5",
    "LI7": "Limit 7",
    "LI10": "Limit 10",
    "L_STAKES_1": "Low Stakes 1",
    "L_STAKES_2": "Low Stakes 2",
    "L_STAKES_5": "Low Stakes 5",
    "H_STAKES_12": "High Stakes 12",
    "H_STAKES_20": "High Stakes 20",
    "H_STAKES_40": "High Stakes 40",
    "MSG_NORESULT": "No matching results!",
    "MSG_NOCOOKIE": "Could not find required cookie! Please make sure cookies are enabled.",
    "HAND_ATTABLE": "at table",
    "HAND_HANDSTARTED": "Hand started",
    "HAND_HANDENDED": "Hand ended",
    "HAND_DEALINGROUND": "Dealing Round",
    "HAND_PLAYER": "Player",
    "HAND_CARDS": "Cards",
    "HAND_BLINDS": "Blinds",
    "HAND_ANTE": "Ante",
    "HAND_ACTIONS": "Actions",
    "HAND_SEAT": "Seat",
    "HAND_NAME": "Name",
    "HAND_AMOUNT": "Amount",
    "HAND_DEAL": "Deal",
    "HAND_ROUND": "Bet Round",
    "HAND_WIN": "Win",
    "HAND_SHOWDOWN": "Showdown",
    "HAND_DEALER": "Dealer",
    "HAND_SB": "SB",
    "HAND_BB": "BB",
    "HAND_AB": "AB",
    "HAND_STB": "Straddle",
    "HAND_POT": "Total Pot:",
    "HAND_RAKE": "Rake:",
    "HAND_POST": "post",
    "HAND_IS": "is",
    "HAND_BBJ": "Bbj contribution",
    "HAND_PLAYERSSEATING": "Players Seating",
    "HAND_PLAYERSTATE": "Player State",
    "STATE_SITOUT": "Sitout",
    "STATE_RESERVED": "Reserved",
    "STATE_EMPTY": "Empty",
    "BOARD_FLOP": "Flop(Board):",
    "BOARD_TURN": "Turn(Board):",
    "BOARD_RIVER": "River(Board):",
    "BOARD_FINAL": "Final(Board):",
    "ACTION_BET": "Bet",
    "ACTION_RAISE": "Raise to",
    "ACTION_CALL": "Call",
    "ACTION_CHECK": "Check",
    "ACTION_FOLD": "Fold",
    "ACTION_PAUS": "Faire une pause",
    "ACTION_BRINGIN": "Bring in",
    "ACTION_ALLIN": "All-in",
    "ACTION_BBJ": "BBJ: ",
    "ACTION_ADJUSTEMENT": "was all-in adjusted",
    "BBJ_WON": "Bad Beat Jackpot Amounts",
    "DECK_HEARTS": "h",
    "DECK_SPADES": "s",
    "DECK_CLUBS": "c",
    "DECK_DIAMONDS": "d",
    "DECK_JACK": "J",
    "DECK_QUEEN": "Q",
    "DECK_KING": "K",
    "DECK_ACE": "A",
    "STR_G_PLAYER_PIN": "Pin:",
    "STR_G_PLAYER_FIRSTNAME": "Firstname: ",
    "STR_G_PLAYER_ADDRESS": "Address: ",
    "STR_G_PLAYER_ZIPCODE": "Zip code: ",
    "STR_G_PLAYER_TOWN": "Town: ",
    "STR_G_BADBEATJACKPOT": "Bad Beat Jackpot",
    "STR_G_CHECK": "Check",
    "STR_G_CALL": "Call",
    "STR_G_CHECKCALLANY": "Check / Call any",
    "STR_G_CALLANY": "Call any",
    "STR_G_BET": "Bet",
    "STR_G_RAISE": "Raise",
    "STR_G_BETRAISEANY": "Bet / Raise any",
    "STR_G_RAISEANY": "Raise any",
    "STR_G_CHECKFOLD": "Check / Fold",
    "STR_G_FOLD": "Fold",
    "STR_G_MUCK": "Muck",
    "STR_G_FOLDANY": "Fold any",
    "STR_BY_DEFAULT": "By default",
    "STR_G_AUTOPOST": "Autopost Blinds",
    "STR_G_SITOUT": "Sitout next hand",
    "STR_G_WAITBIGBLIND": "Wait on big blind",
    "STR_G_BETPOT": "Bet pot",
    "STR_G_RAISEPOT": "Raise pot",
    "STR_G_AUTOPOSTANTE": "Autopost ante",
    "STR_G_OPEN": "Open",
    "STR_G_ALLINFOR": "All-in for",
    "STR_G_BUYINTEXT": "BUY IN",
    "STR_G_SEATRESERVED": "RESERVED",
    "STR_G_MAINPOT": "Main:",
    "STR_G_LEFTPOT": "Left:",
    "STR_G_RIGHTPOT": "Right:",
    "STR_G_SIDEPOT": "SP",
    "STR_G_TOTALPOT": "Total:",
    "STR_G_HANDNO": "Current:",
    "STR_G_PREVHANDNO": "Last:",
    "STR_G_CARDS_ACES": "aces",
    "STR_G_CARDS_DEUCES": "deuces",
    "STR_G_CARDS_THREES": "threes",
    "STR_G_CARDS_FOURS": "fours",
    "STR_G_CARDS_FIVES": "fives",
    "STR_G_CARDS_SIXES": "sixes",
    "STR_G_CARDS_SEVENS": "sevens",
    "STR_G_CARDS_EIGHTS": "eights",
    "STR_G_CARDS_NINES": "nines",
    "STR_G_CARDS_TENS": "tens",
    "STR_G_CARDS_JACKS": "jacks",
    "STR_G_CARDS_QUEENS": "queens",
    "STR_G_CARDS_KINGS": "kings",
    "STR_G_CARD_ACE": "ace",
    "STR_G_CARD_TWO": "two",
    "STR_G_CARD_THREE": "threes",
    "STR_G_CARD_FOUR": "four",
    "STR_G_CARD_FIVE": "five",
    "STR_G_CARD_SIX": "six",
    "STR_G_CARD_SEVEN": "seven",
    "STR_G_CARD_EIGHT": "eight",
    "STR_G_CARD_NINE": "nine",
    "STR_G_CARD_TEN": "ten",
    "STR_G_CARD_JACK": "jack",
    "STR_G_CARD_QUEEN": "queen",
    "STR_G_CARD_KING": "king",
    "STR_G_ANDTEXT": "and",
    "STR_G_KICKERTEXT": "kicker",
    "STR_G_FORLOWTEXT": "for low",
    "STR_G_WIN_HIGHCARD": "Highest card",
    "STR_G_WIN_PAIR": "Pair of",
    "STR_G_WIN_FOURCARDSTRAIGHT": "Four card straight to the",
    "STR_G_WIN_ACEHIGHFOURCARDSTRAIGHT": "Ace high straight",
    "STR_G_WIN_FOURCARDFLUSH": "Four card flush to the",
    "STR_G_WIN_ACEHIGHFOURCARDFLUSH": "Ace high four card flush",
    "STR_G_WIN_TWOPAIR": "Two pair",
    "STR_G_WIN_THREEOFAKIND": "Three of a kind,",
    "STR_G_WIN_STRAIGHT": "Straight to the",
    "STR_G_WIN_ACEHIGHSTRAIGHT": "Ace high straight",
    "STR_G_WIN_FLUSH": "Flush to the",
    "STR_G_WIN_ACEHIGHFLUSH": "Ace high flush",
    "STR_G_WIN_FULLHOUSE": "Full house",
    "STR_G_WIN_FOUROFAKIND": "Four of a kind,",
    "STR_G_WIN_STRAIGHTFLUSH": "Straight flush",
    "STR_G_WIN_ROYALSTRAIGHTFLUSH": "Royal straight flush",
    "STR_G_LOG_SECOND": "2nd Street",
    "STR_G_LOG_THIRD": "3rd Street",
    "STR_G_LOG_FOURTH": "4th Street",
    "STR_G_LOG_FIFTH": "5th Street",
    "STR_G_LOG_SIXTH": "6th Street",
    "STR_G_LOG_SEVENTH": "7th Street",
    "STREET": "Street",
    "CHANGE_CARD": "Exchange",
    "CHANGED_CARDS": "Exchanged cards:",
    "STANDPAT": "Standpat",
    "ROUND_FIRSTSTEP": "First Step",
    "ROUND_PREVSTEP": "Previous Step",
    "ROUND_PLAYHAND": "Play Hand",
    "ROUND_PAUSEHAND": "Pause Hand",
    "ROUND_PLAYBACKSPEED": "Speed:",
    "ROUND_NEXTSTEP": "Next Step",
    "ROUND_LASTSTEP": "Last Step",
    "ROUND_FIRSTHAND": "First Hand",
    "ROUND_PREVHAND": "Previous Hand",
    "ROUND_NEXTHAND": "Next Hand",
    "ROUND_LASTHAND": "Last Hand",
    "WINTYPE_HI": "Hi",
    "WINTYPE_LO": "Low",
    "WINTYPE_HILO": "Winner",
    "BOUNTY": "Bounty",
    "HAND_DSB": "SB invalide",
    "SCORE": "Score"
};

export default language;